name: Build Rust App

on:
  push:
    branches: [ Main ]
  workflow_dispatch:

jobs:
  build:
    name: Cross Compile
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - aarch64-unknown-linux-gnu
          - armv7-unknown-linux-gnueabihf
          - x86_64-pc-windows-gnu
          - x86_64-apple-darwin

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Rust target
        run: rustup target add ${{ matrix.target }}

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential gcc-multilib

      - name: Build project
        run: cargo build --release --target=${{ matrix.target }}

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: filetidy-${{ matrix.target }}
          path: target/${{ matrix.target }}/release/filetidy*
