name: Build Rust Binary

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions/setup-rust@v1
        with:
          rust-version: stable

      - name: Install cross
        run: cargo install cross

      - name: Build for aarch64
        run: cross build --release --target aarch64-unknown-linux-gnu

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: filetidy-aarch64
          path: target/aarch64-unknown-linux-gnu/release/filetidy
